<?php
/**
 * @file
 * Basic functionality for the tripal analysis expression module.
 */

/**
 * @defgroup tripal_biomaterial Tripal Analysis Expression
 * @ingroup tripal_modules *** is this right?
 * @{
 * Integrates the several tables from the Chado Mage module with
 * the Analysis module.
 * @}
 */
require_once "includes/tripal_biomaterial.fields.inc";
require_once "theme/tripal_biomaterial.theme.inc";
require_once "api/tripal_biomaterial.api.inc";

/**
 * Implements hook_help().
 *
 * Display help and module information.
 *
 * @ingroup tripal_biomaterial
 */
function tripal_biomaterial_help($path, $arg) {
  switch ($path) {

    // Both of the following cases should display the below HTML.
    case 'admin/tripal/extension/tripal_biomaterial/help' :
    case 'admin/help#tripal_biomaterial' : {
      $ret_val = "<b>" . t("Biomaterial") . "</b> - " . t("The biomaterial content type represents the Chado biomaterial table of the Chado MAGE module. The biomaterial content type is analogous to the NCBI ");
      $ret_val .= l(t("BioSample."), "http://www.ncbi.nlm.nih.gov/books/NBK169436/") . " ";
      $ret_val .= "<br><br>" . l(t("Biomaterial Administrative Pages"), "admin/tripal/extension/tripal_biomaterial/content_types/biomaterial");
      $ret_val .= "<br>" . l(t("Biomaterial Help"), "admin/tripal/extension/tripal_biomaterial/content_types/biomaterial/help");
      $ret_val .= "<br>" . l(t("Biomaterial Loader"), "admin/tripal/loaders/chado_biosample_loader");
      $ret_val .= "<br>" . l(t("BioSample submission template"), "https://submit.ncbi.nlm.nih.gov/biosample/template/");
      return $ret_val;
      break;
    }
  }
}

/**
 * Implements hook_permission().
 *
 *
 * @ingroup tripal_biomaterial
 */
function tripal_biomaterial_permission() {

}

/**
 * Implements hook_menu().
 *
 * Admin pages are no longer necessary for biomaterials/biosamples.
 *
 * @ingroup tripal_expression
 */
function tripal_biomaterial_menu() {
  $items = [];

  // Admin configuration group.
  $items['admin/tripal/extension/tripal_biomaterial'] = [
    'title' => 'Biomaterial',
    'description' => 'Administrative pages for the Tripal Biomaterial module.',
    'access arguments' => ['administer tripal biomaterial'],
  ];

  // Module help pages.
  $items['admin/tripal/extension/tripal_biomaterial/help'] = [
    'title' => 'Biomaterials Help',
    'description' => 'A description of expression module content types and loaders.',
    'access arguments' => ['administer tripal Biomaterial'],
    'weight' => 10,
  ];

  return $items;
}

/**
 * Implements hook_views_api().
 *
 * Essentially this hook tells drupal that there is views support for
 *  for this module which then includes tripal_db.views.inc where all the
 *  views integration code is located.
 *
 * @ingroup tripal_biomaterial
 */
function tripal_biomaterial_views_api() {
  return [
    'api' => 3.0,
  ];
}

/**
 * Implements hook_theme().
 *
 * This function informs drupal of the themes included in this modules.
 *  An base, help, and teaser template are included for the four content
 *  types defined by this module: analysis: expression, arraydesign,
 *  biomaterial, and protocol. Additional templates include a protocol
 *  template for the analysis: expression content type and a variable
 *  expression template for the feature content type.
 *
 * ***documentation of parameters here????
 *
 * @ingroup tripal_biomaterial
 */
function tripal_biomaterial_theme($existing, $type, $theme, $path) {
  $core_path = drupal_get_path('module', 'tripal_core');

  $items = [
    'tripal_biomaterial_help' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_help',
      'path' => "$path/theme/templates",
    ],
    'tripal_biomaterial_base' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_base',
      'path' => "$path/theme/templates",
    ],
    'tripal_biomaterial_protocols' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_protocols',
      'path' => "$path/theme/templates",
    ],
    'tripal_biomaterial_teaser' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_teaser',
      'path' => "$path/theme/templates",
    ],
    'node__chado_biomaterial' => [
      'template' => 'node--chado-generic',
      'render element' => 'node',
      'base hook' => 'node',
      'path' => "$core_path/theme/templates",
    ],
    'tripal_biomaterial_base' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_base',
      'path' => "$path/theme/templates",
    ],
    'tripal_biomaterial_properties' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_properties',
      'path' => "$path/theme/templates",
    ],
    'tripal_biomaterial_references' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_references',
      'path' => "$path/theme/templates",
    ],
    'tripal_biomaterial_teaser' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_teaser',
      'path' => "$path/theme/templates",
    ],
    'tripal_biomaterial_help' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_biomaterial_help',
      'path' => "$path/theme/templates",
    ],
    'tripal_organism_biomaterial' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_organism_biomaterial',
      'path' => "$path/theme/templates",
    ],
    'tripal_analysis_biomaterial' => [
      'variables' => ['node' => NULL],
      'template' => 'tripal_analysis_biomaterial',
      'path' => "$path/theme/templates",
    ],
  ];
  return $items;
}
